---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.component_id}}
  namespace: openshift-gitops
  labels:
    argocd/app-name: ${{values.component_id}}
    rht-gitops.com/openshift-gitops: ${{values.component_id}}-gitops
  annotations:
    argocd/app-name: ${{values.component_id}}
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: ${{values.destination}}
    targetRevision: HEAD
    path: ./helm/app
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.namespace}}
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
